/****
**************************************************** **************************************************** **************************************************** ****************************
* @file qspi_w25q64.c
* @version V1.0
* @date 2020-8-12
* @author Anti-Ke Technology
* @brief QSPI drives W25Qxx related functions, and the provided read and write functions are directly operated by HAL library functions
**************************************************** **************************************************** **************************************************** ********************************
* @description
*
* Experimental platform: Antike STM32H750VBT6 core board (model: FK750M3-VBT6)

>>>>> File Description:
*
* 1. The routine refers to the official driver file stm32h743i_eval_qspi.c
* 2. The routine uses QUADSPI_BK1
* 3. The read and write functions provided are directly operated by HAL library functions, without DMA and interrupts
* 4. The default configuration QSPI drive clock is 125M
*
>>>>> Important Notes:
*
* 1. The erasing time of W25QXX is limited!!! The typical reference values ??given in the manual are: 4K-45ms, 32K-120ms, 64K-150ms, whole chip erase 20S
*
* 2. The writing time of W25QXX is limited!!! The typical reference value given in the manual is: 256 bytes-0.4ms, which is 1M bytes/s (the actual measurement is about 600K bytes/s)
*
* 3. If you use the library function to read directly, then whether to use DMA, whether to open the Cache, the optimization level of the compiler, and the location of the data storage area (internal TCM SRAM or AXI SRAM) will affect the reading speed.
*
* 4. If the memory mapping mode is used, the read performance is only related to the QSPI drive clock and whether the Cache is enabled
*
* 5. Use library functions for direct reading, keil version 5.30, compiler AC6.14, compilation level Oz image size, read speed is 6.7M bytes/S, data is placed in TCM SRAM or AXI SRAM
* All are similar results, because the CPU is very inefficient to directly access peripheral registers, and if the HAL library is used to read directly, the speed is very slow
*
* 6. If MDMA is used for reading, it can reach 55.56M bytes/S, and if memory mapping mode is used, it can reach 59.7M/s
*
* 7. The maximum driving frequency allowed by W25Q64JV is 133MHz, and the maximum driving frequency of 750 QSPI is also 133MHz, but for the direct reading of HAL library functions, there will be no performance improvement if the driving clock exceeds 15M
*
* 8. For direct reading in memory mapping mode, there will be no performance improvement if the drive clock exceeds 127.5M. Because the QSPI core clock is limited to a maximum of 250M, it is recommended that the actual QSPI drive clock should not exceed 125M.
* For specific clock configuration, please refer to the SystemClock_Config function
*
* 9. In actual use, when the data is relatively large, it is recommended to use 64K or 32K erasing, the erasing time is longer than 4K erasing blocks
*
**************************************************** **************************************************** **************************************************** ********************************FANKE*****
***/
#include "qspi_w25q64.h"

extern QSPI_HandleTypeDef hqspi;	// Define the QSPI handle. The variable naming generated by cubeMX is reserved here, which is convenient for users to reference and transplant.
/**************************************************** ****************************************************
* Function name: HAL_QSPI_MspInit
* Entry parameters: hqspi - the variable defined by QSPI_HandleTypeDef, which means the defined QSPI handle
* return value: none
* Function: QSPI pin initialization function
* Description: This function will be called by the MX_QUADSPI_Init function
**************************************************************************************************/

void _HAL_QSPI_MspInit(QSPI_HandleTypeDef* hqspi)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  if(hqspi->Instance==QUADSPI)
  {
    __HAL_RCC_QSPI_CLK_ENABLE();	// Enable QSPI clock
    
    GPIO_QUADSPI_CLK_ENABLE;	        // Enable QUADSPI_CLK IO port clock
    GPIO_QUADSPI_BK1_NCS_ENABLE;	// Enable QUADSPI_BK1_NCS IO port clock
    GPIO_QUADSPI_BK1_IO0_ENABLE;	// Enable QUADSPI_BK1_IO0 IO port clock
    GPIO_QUADSPI_BK1_IO1_ENABLE;	// Enable QUADSPI_BK1_IO1 IO port clock
    GPIO_QUADSPI_BK1_IO2_ENABLE;	// Enable QUADSPI_BK1_IO2 IO port clock
    GPIO_QUADSPI_BK1_IO3_ENABLE;	// Enable QUADSPI_BK1_IO3 IO port clock
    
    /******************************************************  
    PB2     ------> QUADSPI_CLK	
    PB6     ------> QUADSPI_BK1_NCS 		
    PD11    ------> QUADSPI_BK1_IO0
    PD12    ------> QUADSPI_BK1_IO1		
    PE2     ------> QUADSPI_BK1_IO2	
    PD13    ------> QUADSPI_BK1_IO3
    *******************************************************/
    
    GPIO_InitStruct.Mode 	= GPIO_MODE_AF_PP;				// Multiplexed push-pull output mode
    GPIO_InitStruct.Pull 	= GPIO_NOPULL;					// no pull-down
    
    GPIO_InitStruct.Speed 	= GPIO_SPEED_FREQ_VERY_HIGH;	                // Super high speed IO port speed
    
    GPIO_InitStruct.Pin 	= QUADSPI_CLK_PIN;				// QUADSPI_CLK pin
    GPIO_InitStruct.Alternate 	= QUADSPI_CLK_AF;				// QUADSPI_CLK multiplex
    HAL_GPIO_Init(QUADSPI_CLK_PORT, &GPIO_InitStruct);			        // initialization QUADSPI_CLK pin
    
    GPIO_InitStruct.Pin 	= QUADSPI_BK1_NCS_PIN;			        // QUADSPI_BK1_NCS pin
    GPIO_InitStruct.Alternate 	= QUADSPI_BK1_NCS_AF;			        // QUADSPI_BK1_NCS multiplex
    HAL_GPIO_Init(QUADSPI_BK1_NCS_PORT, &GPIO_InitStruct);                      // initialization QUADSPI_BK1_NCS pin
    
    GPIO_InitStruct.Pin 	= QUADSPI_BK1_IO0_PIN;			        // QUADSPI_BK1_IO0 pin
    GPIO_InitStruct.Alternate 	= QUADSPI_BK1_IO0_AF;			        // QUADSPI_BK1_IO0 multiplex
    HAL_GPIO_Init(QUADSPI_BK1_IO0_PORT, &GPIO_InitStruct);	                // initialization QUADSPI_BK1_IO0 pin	
    
    GPIO_InitStruct.Pin 	= QUADSPI_BK1_IO1_PIN;			        // QUADSPI_BK1_IO1 pin
    GPIO_InitStruct.Alternate 	= QUADSPI_BK1_IO1_AF;			        // QUADSPI_BK1_IO1 multiplex
    HAL_GPIO_Init(QUADSPI_BK1_IO1_PORT, &GPIO_InitStruct);                      // initialization QUADSPI_BK1_IO1 pin
    
    GPIO_InitStruct.Pin 	= QUADSPI_BK1_IO2_PIN;			        // QUADSPI_BK1_IO2 pin
    GPIO_InitStruct.Alternate 	= QUADSPI_BK1_IO2_AF;			        // QUADSPI_BK1_IO2 multiplex
    HAL_GPIO_Init(QUADSPI_BK1_IO2_PORT, &GPIO_InitStruct);	                // initialization QUADSPI_BK1_IO2 pin			
    
    GPIO_InitStruct.Pin 	= QUADSPI_BK1_IO3_PIN;			        // QUADSPI_BK1_IO3 pin
    GPIO_InitStruct.Alternate 	= QUADSPI_BK1_IO3_AF;			        // QUADSPI_BK1_IO3 multiplex
    HAL_GPIO_Init(QUADSPI_BK1_IO3_PORT, &GPIO_InitStruct);	                // initialization QUADSPI_BK1_IO3 pin
  }
}

/***************************************************** ************************************************
* Function name: MX_QUADSPI_Init
* Entry parameters: none
* return value: none
* Function: Initialize QSPI configuration
* Description: none
****************************************************************************************************/

void MX_QUADSPI_Init(void)
{
  hqspi.Instance 					= QUADSPI;									// QSPI peripheral
  /*This routine selects pll2_r_ck as the core clock of QSPI, the speed is 250M, and then divided by 2 to get the 125M drive clock,
  For the setting of the QSPI core clock, please refer to the SystemClock_Config function in the main.c file*/
  // It should be noted that when using memory mapping mode, the frequency division factor here cannot be set to 0! ! Otherwise read error
  hqspi.Init.ClockPrescaler 		= 1;					// Clock frequency division value, divide the QSPI core clock by 1+1 to get the QSPI communication drive clock
  hqspi.Init.FifoThreshold 		= 32;					// FIFO threshold
  hqspi.Init.SampleShifting		= QSPI_SAMPLE_SHIFTING_HALFCYCLE;	// Sampling after half a CLK cycle
  hqspi.Init.FlashSize 			= 22;					// Flash size, the number of bytes in FLASH = 2^[FSIZE+1], the core board uses W25Q64 with 8M bytes, which is set to 22 here
  hqspi.Init.ChipSelectHighTime         = QSPI_CS_HIGH_TIME_1_CYCLE;		// The time the chip select remains high
  hqspi.Init.ClockMode 			= QSPI_CLOCK_MODE_3;			// Mode 3
  hqspi.Init.FlashID 			= QSPI_FLASH_ID_1;			// Using QSPI1
  hqspi.Init.DualFlash 			= QSPI_DUALFLASH_DISABLE;		// Disable Dual Flash Mode
  
  HAL_QSPI_Init(&hqspi); // Initial configuration
}

/****************************************************** ************************************************
* Function name: QSPI_W25Qxx_Init
* Entry parameters: none
* Return value: QSPI_W25Qxx_OK - initialization successful, W25Qxx_ERROR_INIT - initialization error
* Function: Initialize QSPI configuration, read W25Q64ID
* Description: none
**************************************************************************************************/

int8_t QSPI_W25Qxx_Init(void)
{
  uint32_t	Device_ID;	// Device ID
  //_HAL_QSPI_MspInit(&hqspi);
  //MX_QUADSPI_Init();							// Initialize QSPI configuration
  QSPI_W25Qxx_Reset();							// reset device
  Device_ID = QSPI_W25Qxx_ReadID(); 		// Read Device ID
  
  if( Device_ID == W25Qxx_FLASH_ID )		// to match
  {
    //printf ("W25Q64 OK,flash ID:%X\r\n",Device_ID);		// Initialization successful
    return QSPI_W25Qxx_OK;			// return success flag		
  }
  else
  {
    //printf ("W25Q64 ERROR!!!!!  ID:%X\r\n",Device_ID);	// initialization failed	
    return W25Qxx_ERROR_INIT;		// return error flag
  }	
}

/****************************************************** ************************************************
* Function name: QSPI_W25Qxx_AutoPollingMemReady
* Entry parameters: none
* Return value: QSPI_W25Qxx_OK - communication ended normally, W25Qxx_ERROR_AUTOPOLLING - polling waiting for no response
* Function: Use the automatic polling flag to query and wait for the end of the communication
* Description: The sub-function should be called for each communication, waiting for the end of the communication to avoid wrong operations
**************************************************************************************************/

int8_t QSPI_W25Qxx_AutoPollingMemReady(void)
{
  QSPI_CommandTypeDef     s_command;	   // QSPI transfer configuration
  QSPI_AutoPollingTypeDef s_config;		// Polling comparison related configuration parameters
  
  s_command.InstructionMode   = QSPI_INSTRUCTION_1_LINE;			// 1-Wire Command Mode
  s_command.AddressMode       = QSPI_ADDRESS_NONE;					// no address mode
  s_command.AlternateByteMode = QSPI_ALTERNATE_BYTES_NONE;			//	no alternate bytes 
  s_command.DdrMode           = QSPI_DDR_MODE_DISABLE;	     	 	// Disable DDR mode
  s_command.DdrHoldHalfCycle  = QSPI_DDR_HHC_ANALOG_DELAY;	   	// Data delay in DDR mode, not used here
  s_command.SIOOMode          = QSPI_SIOO_INST_EVERY_CMD;	   	//	Send a command every time data is transferred	
  s_command.DataMode          = QSPI_DATA_1_LINE;						// 1-Wire Data Mode
  s_command.DummyCycles       = 0;											//	Number of empty cycles
  s_command.Instruction       = W25Qxx_CMD_ReadStatus_REG1;	   // Read Status Information Register
  
  // Keep querying the W25Qxx_CMD_ReadStatus_REG1 register, and keep comparing the W25Qxx_Status_REG1_BUSY in the read status byte with 0
  // Read bit 0 of status register 1 (read-only), the Busy flag bit, will be set to 1 when erasing/writing data/writing commands, and 0 when idle or communication ends
  
  s_config.Match           = 0;   									//	match value
  s_config.MatchMode       = QSPI_MATCH_MODE_AND;	      	//	AND operation
  s_config.Interval        = 0x10;	                     	//	polling interval
  s_config.AutomaticStop   = QSPI_AUTOMATIC_STOP_ENABLE;	// Auto stop mode
  s_config.StatusBytesSize = 1;	                        	//	Status bytes
  s_config.Mask            = W25Qxx_Status_REG1_BUSY;	   // Masks the status byte received in polling mode and compares only the bits that need to be used
  
  // Send poll wait command
  if (HAL_QSPI_AutoPolling(&hqspi, &s_command, &s_config, HAL_QPSI_TIMEOUT_DEFAULT_VALUE) != HAL_OK)
  {
    return W25Qxx_ERROR_AUTOPOLLING; // Polling waiting for no response
  }
  return QSPI_W25Qxx_OK; // Communication ended normally
  
}

/****************************************************** ************************************************
* Function name: QSPI_W25Qxx_Reset
* Entry parameters: none
* Return value: QSPI_W25Qxx_OK - reset successful, W25Qxx_ERROR_INIT - initialization error
* Function: reset device
* Description: none
**************************************************************************************************/

int8_t QSPI_W25Qxx_Reset(void)	
{
  QSPI_CommandTypeDef s_command;	// QSPI transfer configuration
  
  s_command.InstructionMode   = QSPI_INSTRUCTION_1_LINE;   	// 1-Wire Command Mode
  s_command.AddressMode       = QSPI_ADDRESS_NONE;   			// no address mode
  s_command.AlternateByteMode = QSPI_ALTERNATE_BYTES_NONE; 	// no alternate bytes 
  s_command.DdrMode           = QSPI_DDR_MODE_DISABLE;     	// Disable DDR mode
  s_command.DdrHoldHalfCycle  = QSPI_DDR_HHC_ANALOG_DELAY; 	// Data delay in DDR mode, not used here
  s_command.SIOOMode          = QSPI_SIOO_INST_EVERY_CMD;	 	// Send a command every time data is transferred
  s_command.DataMode          = QSPI_DATA_NONE;       			// no data mode	
  s_command.DummyCycles       = 0;                     			// Number of empty cycles
  s_command.Instruction       = W25Qxx_CMD_EnableReset;       // Execute the reset enable command
  
  // Send reset enable command
  if (HAL_QSPI_Command(&hqspi, &s_command, HAL_QPSI_TIMEOUT_DEFAULT_VALUE) != HAL_OK) 
  {
    return W25Qxx_ERROR_INIT;			// If sending fails, return an error message
  }
  // Use automatic polling flags and wait for the end of communication
  if (QSPI_W25Qxx_AutoPollingMemReady() != QSPI_W25Qxx_OK)
  {
    return W25Qxx_ERROR_AUTOPOLLING;	// Polling waiting for no response
  }
  
  s_command.Instruction  = W25Qxx_CMD_ResetDevice;     // Reset Device Command    
  
  //Send reset device command
  if (HAL_QSPI_Command(&hqspi, &s_command, HAL_QPSI_TIMEOUT_DEFAULT_VALUE) != HAL_OK) 
  {
    return W25Qxx_ERROR_INIT;		  // If sending fails, return an error message
  }
  // Use automatic polling flags and wait for the end of communication
  if (QSPI_W25Qxx_AutoPollingMemReady() != QSPI_W25Qxx_OK)
  {
    return W25Qxx_ERROR_AUTOPOLLING;	// Polling waiting for no response
  }	
  return QSPI_W25Qxx_OK;	// reset successfully
}

/******************************************************* ************************************************
* Function name: QSPI_W25Qxx_ReadID
* Entry parameters: none
* Return value: W25Qxx_ID - read device ID, W25Qxx_ERROR_INIT - communication, initialization error
* Function: Initialize QSPI configuration, read device ID
* Description: none
**************************************************************************************************/

uint32_t QSPI_W25Qxx_ReadID(void)	
{
  QSPI_CommandTypeDef s_command;	// QSPI transfer configuration
  uint8_t	QSPI_ReceiveBuff[3];		// Store the data read by QSPI
  uint32_t	W25Qxx_ID;					// Device ID
  
  s_command.InstructionMode   = QSPI_INSTRUCTION_1_LINE;    // 1-Wire Command Mode
  s_command.AddressSize       = QSPI_ADDRESS_24_BITS;     	 // 24-bit address
  s_command.AlternateByteMode = QSPI_ALTERNATE_BYTES_NONE;  // no alternate bytes 
  s_command.DdrMode           = QSPI_DDR_MODE_DISABLE;      // Disable DDR mode
  s_command.DdrHoldHalfCycle  = QSPI_DDR_HHC_ANALOG_DELAY;  // Data delay in DDR mode, not used here
  s_command.SIOOMode          = QSPI_SIOO_INST_EVERY_CMD;	 // Send a command every time data is transferred
  s_command.AddressMode		 = QSPI_ADDRESS_NONE;   		 // no address mode
  s_command.DataMode			 = QSPI_DATA_1_LINE;       	 // 1-Wire Data Mode
  s_command.DummyCycles 		 = 0;                   		 // Number of empty cycles
  s_command.NbData 				 = 3;                          // Length of transmitted data
  s_command.Instruction 		 = W25Qxx_CMD_JedecID;         // Execute the read device ID command
  
  // send instructions
  if (HAL_QSPI_Command(&hqspi, &s_command, HAL_QPSI_TIMEOUT_DEFAULT_VALUE) != HAL_OK) 
  {
    //		return W25Qxx_ERROR_INIT;		//If sending fails, return an error message
  }
  // Receive data
  if (HAL_QSPI_Receive(&hqspi, QSPI_ReceiveBuff, HAL_QPSI_TIMEOUT_DEFAULT_VALUE) != HAL_OK) 
  {
    //		return W25Qxx_ERROR_TRANSMIT;  // If the reception fails, return an error message
  }
  // Combine the resulting data into an ID
  W25Qxx_ID = (QSPI_ReceiveBuff[0] << 16) | (QSPI_ReceiveBuff[1] << 8 ) | QSPI_ReceiveBuff[2];
  
  return W25Qxx_ID; // return ID
}


/**************************************************** ****************************************************
* Function name: QSPI_W25Qxx_MemoryMappedMode
* Entry parameters: none
* Return value: QSPI_W25Qxx_OK - write enable success, W25Qxx_ERROR_WriteEnable - write enable failure
* Function: Set QSPI to memory mapping mode
* Description: When set to memory mapping mode, only read, not write! ! !
***************************************************************************************************/

int8_t QSPI_W25Qxx_MemoryMappedMode(void)
{
  QSPI_CommandTypeDef      s_command;				 // QSPI transfer configuration
  QSPI_MemoryMappedTypeDef s_mem_mapped_cfg;	 // Memory Map Access Parameters
  
  s_command.InstructionMode   = QSPI_INSTRUCTION_1_LINE;    		// 1-Wire Command Mode
  s_command.AddressSize       = QSPI_ADDRESS_24_BITS;            // 24-bit address
  s_command.AlternateByteMode = QSPI_ALTERNATE_BYTES_NONE;  		// no alternate bytes 
  s_command.DdrMode           = QSPI_DDR_MODE_DISABLE;     		// Disable DDR mode
  s_command.DdrHoldHalfCycle  = QSPI_DDR_HHC_ANALOG_DELAY; 		// Data delay in DDR mode, not used here
  s_command.SIOOMode          = QSPI_SIOO_INST_EVERY_CMD;			// Send a command every time data is transferred	
  s_command.AddressMode 		 = QSPI_ADDRESS_4_LINES; 				// 4-Wire Address Mode
  s_command.DataMode    		 = QSPI_DATA_4_LINES;    				// 4-wire data mode
  s_command.DummyCycles 		 = 6;                    				// Number of empty cycles
  s_command.Instruction 		 = W25Qxx_CMD_FastReadQuad_IO; 		// In 1-4-4 mode (1-line command, 4-line address, 4-line data), fast read command
  
  s_mem_mapped_cfg.TimeOutActivation = QSPI_TIMEOUT_COUNTER_DISABLE; // Timeout counter disabled, nCS remains active
  s_mem_mapped_cfg.TimeOutPeriod     = 0;									 // Timeout Judgment Period
  
  QSPI_W25Qxx_Reset();		// Reset W25Qxx
  
  if (HAL_QSPI_MemoryMapped(&hqspi, &s_command, &s_mem_mapped_cfg) != HAL_OK)	// configure
  {
    return W25Qxx_ERROR_MemoryMapped; 	// Error setting memory map mode
  }
  
  return QSPI_W25Qxx_OK; // Configured successfully
}
/**************************************************** ****************************************************
* Function name: QSPI_W25Qxx_WriteEnable
* Entry parameters: none
* Return value: QSPI_W25Qxx_OK - write enable success, W25Qxx_ERROR_WriteEnable - write enable failure
* Function: Send write enable command
* Description: none
**************************************************** ****************************************************/
int8_t QSPI_W25Qxx_WriteEnable(void)
{
  QSPI_CommandTypeDef     s_command;	   // QSPI transfer configuration
  QSPI_AutoPollingTypeDef s_config;		// Polling comparison related configuration parameters
  
  s_command.InstructionMode   	= QSPI_INSTRUCTION_1_LINE;    	// 1-Wire Command Mode
  s_command.AddressMode 			= QSPI_ADDRESS_NONE;   		      // no address mode
  s_command.AlternateByteMode 	= QSPI_ALTERNATE_BYTES_NONE;  	// no alternate bytes 
  s_command.DdrMode           	= QSPI_DDR_MODE_DISABLE;      	// Disable DDR mode
  s_command.DdrHoldHalfCycle  	= QSPI_DDR_HHC_ANALOG_DELAY;  	// DData delay in DR mode, not used here
  s_command.SIOOMode          	= QSPI_SIOO_INST_EVERY_CMD;		// Send a command every time data is transferred	
  s_command.DataMode 				= QSPI_DATA_NONE;       	      // no data mode
  s_command.DummyCycles 			= 0;                   	         // Number of empty cycles
  s_command.Instruction	 		= W25Qxx_CMD_WriteEnable;      	// Send write enable command
  
  // Send write enable command
  if (HAL_QSPI_Command(&hqspi, &s_command, HAL_QPSI_TIMEOUT_DEFAULT_VALUE) != HAL_OK) 
  {
    return W25Qxx_ERROR_WriteEnable;	//
  }
  // Keep querying the W25Qxx_CMD_ReadStatus_REG1 register, and keep comparing the W25Qxx_Status_REG1_WEL in the read status byte with 0x02
  // Read the first bit of status register 1 (read-only), WEL write enable flag bit, when the flag bit is 1, it means that the write operation can be performed
  s_config.Match           = 0x02;  								// match value
  s_config.Mask            = W25Qxx_Status_REG1_WEL;	 		// Read the first bit of the status register 1 (read-only), the WEL write enable flag bit, when the flag bit is 1, it means that the write operation can be performed
  s_config.MatchMode       = QSPI_MATCH_MODE_AND;			 	// AND operation
  s_config.StatusBytesSize = 1;									 	// Status bytes
  s_config.Interval        = 0x10;							 		// polling interval
  s_config.AutomaticStop   = QSPI_AUTOMATIC_STOP_ENABLE;	// Auto stop mode
  
  s_command.Instruction    = W25Qxx_CMD_ReadStatus_REG1;	// Read Status Information Register
  s_command.DataMode       = QSPI_DATA_1_LINE;					// 1-Wire Data Mode
  s_command.NbData         = 1;										// Data length
  
  // Send poll wait command	
  if (HAL_QSPI_AutoPolling(&hqspi, &s_command, &s_config, HAL_QPSI_TIMEOUT_DEFAULT_VALUE) != HAL_OK)
  {
    return W25Qxx_ERROR_AUTOPOLLING; 	// Polling waiting for no response
  }	
  return QSPI_W25Qxx_OK;  // Communication ended normally
}

/****************************************************** ************************************************
*
* Function name: QSPI_W25Qxx_SectorErase
*
* Entry parameters: SectorAddress - the address to erase
*
* Return value: QSPI_W25Qxx_OK - erase successfully
* W25Qxx_ERROR_Erase - Erase failed
* W25Qxx_ERROR_AUTOPOLLING - polling waiting for no response
*
* Function: Perform sector erase operation, erase 4K bytes each time
*
* Note: 1. According to the erasure reference time given in the W25Q64JV data sheet, the typical value is 45ms, and the maximum value is 400ms
* 2. The actual erasing speed may be greater than 45ms or less than 45ms
* 3. The longer the flash is used, the longer it takes to erase
*
****************************************************************************************************/

int8_t QSPI_W25Qxx_SectorErase(uint32_t SectorAddress)	
{
  QSPI_CommandTypeDef s_command;	// QSPI transfer configuration
  
  s_command.InstructionMode   	= QSPI_INSTRUCTION_1_LINE;    // 1-Wire Command Mode
  s_command.AddressSize       	= QSPI_ADDRESS_24_BITS;       // 24-bit address mode
  s_command.AlternateByteMode 	= QSPI_ALTERNATE_BYTES_NONE;  //	no alternate bytes 
  s_command.DdrMode           	= QSPI_DDR_MODE_DISABLE;      // Disable DDR mode
  s_command.DdrHoldHalfCycle  	= QSPI_DDR_HHC_ANALOG_DELAY;  // Data delay in DDR mode, not used here
  s_command.SIOOMode          	= QSPI_SIOO_INST_EVERY_CMD;	// Send a command every time data is transferred
  s_command.AddressMode 			= QSPI_ADDRESS_1_LINE;        // 1-Wire Address Mode
  s_command.DataMode 				= QSPI_DATA_NONE;             // no data
  s_command.DummyCycles 			= 0;                          // Number of empty cycles
  s_command.Address           	= SectorAddress;              // address to erase
  s_command.Instruction	 		= W25Qxx_CMD_SectorErase;     // Sector Erase Command
  
  // send write enable
  if (QSPI_W25Qxx_WriteEnable() != QSPI_W25Qxx_OK)
  {
    return W25Qxx_ERROR_WriteEnable;		// write enable failed
  }
  // Issue the erase command
  if (HAL_QSPI_Command(&hqspi, &s_command, HAL_QPSI_TIMEOUT_DEFAULT_VALUE) != HAL_OK)
  {
    return W25Qxx_ERROR_Erase;				// Erase failed
  }
  // Use automatic polling flags to wait for the end of the erase 
  if (QSPI_W25Qxx_AutoPollingMemReady() != QSPI_W25Qxx_OK)
  {
    return W25Qxx_ERROR_AUTOPOLLING;		// Polling waiting for no response
  }
  return QSPI_W25Qxx_OK; // Erase successful
}
/**************************************************** ****************************************************
*
* Function name: QSPI_W25Qxx_BlockErase_32K
*
* Entry parameters: SectorAddress - the address to erase
*
* Return value: QSPI_W25Qxx_OK - erase successfully
* W25Qxx_ERROR_Erase - Erase failed
* W25Qxx_ERROR_AUTOPOLLING - polling waiting for no response
*
* Function: perform block erase operation, erase 32K bytes each time
*
* Note: 1. According to the erasure reference time given in the W25Q64JV data sheet, the typical value is 120ms, and the maximum value is 1600ms
* 2. The actual erasing speed may be greater than 120ms or less than 120ms
* 3. The longer the flash is used, the longer it takes to erase
*
************************************************************************************************/

int8_t QSPI_W25Qxx_BlockErase_32K (uint32_t SectorAddress)	
{
  QSPI_CommandTypeDef s_command;	// QSPI transfer configuration
  
  s_command.InstructionMode   	= QSPI_INSTRUCTION_1_LINE;    // 1-Wire Command Mode
  s_command.AddressSize       	= QSPI_ADDRESS_24_BITS;       // 24-bit address mode
  s_command.AlternateByteMode 	= QSPI_ALTERNATE_BYTES_NONE;  //	no alternate bytes 
  s_command.DdrMode           	= QSPI_DDR_MODE_DISABLE;      // Disable DDR mode
  s_command.DdrHoldHalfCycle  	= QSPI_DDR_HHC_ANALOG_DELAY;  // Data delay in DDR mode, not used here
  s_command.SIOOMode          	= QSPI_SIOO_INST_EVERY_CMD;	// Send a command every time data is transferred
  s_command.AddressMode 			= QSPI_ADDRESS_1_LINE;        // 1-Wire Address Mode
  s_command.DataMode 				= QSPI_DATA_NONE;             // no data
  s_command.DummyCycles 			= 0;                          // Number of empty cycles
  s_command.Address           	= SectorAddress;              // address to erase
  s_command.Instruction	 		= W25Qxx_CMD_BlockErase_32K;  // Block erase command, erase 32K bytes each time
  
  // send write enable	
  if (QSPI_W25Qxx_WriteEnable() != QSPI_W25Qxx_OK)
  {
    return W25Qxx_ERROR_WriteEnable;		// write enable failed
  }
  // Issue the erase command
  if (HAL_QSPI_Command(&hqspi, &s_command, HAL_QPSI_TIMEOUT_DEFAULT_VALUE) != HAL_OK)
  {
    return W25Qxx_ERROR_Erase;				// Erase failed
  }
  //Use automatic polling flags to wait for the end of the erase 
  if (QSPI_W25Qxx_AutoPollingMemReady() != QSPI_W25Qxx_OK)
  {
    return W25Qxx_ERROR_AUTOPOLLING;		// Polling waiting for no response
  }
  return QSPI_W25Qxx_OK;	// Erase successful
}

/***************************************************** ************************************************
*
* Function name: QSPI_W25Qxx_BlockErase_64K
*
* Entry parameters: SectorAddress - the address to erase
*
* Return value: QSPI_W25Qxx_OK - erase successfully
* W25Qxx_ERROR_Erase - Erase failed
* W25Qxx_ERROR_AUTOPOLLING - polling waiting for no response
*
* Function: perform block erase operation, erase 64K bytes each time
*
* Note: 1. According to the erasure reference time given in the W25Q64JV data sheet, the typical value is 150ms, and the maximum value is 2000ms
* 2. The actual erasing speed may be greater than 150ms or less than 150ms
* 3. The longer the flash is used, the longer it takes to erase
* 4. It is recommended to use 64K erasing for actual use, and the erasing time is the fastest
*
*************************************************************************************************/

int8_t QSPI_W25Qxx_BlockErase_64K (uint32_t SectorAddress)	
{
  QSPI_CommandTypeDef s_command;	// QSPI transfer configuration
  
  s_command.InstructionMode   	= QSPI_INSTRUCTION_1_LINE;    // 1-Wire Command Mode
  s_command.AddressSize       	= QSPI_ADDRESS_24_BITS;       // 24-bit address mode
  s_command.AlternateByteMode 	= QSPI_ALTERNATE_BYTES_NONE;  //	no alternate bytes 
  s_command.DdrMode           	= QSPI_DDR_MODE_DISABLE;      // Disable DDR mode
  s_command.DdrHoldHalfCycle  	= QSPI_DDR_HHC_ANALOG_DELAY;  // Data delay in DDR mode, not used here
  s_command.SIOOMode          	= QSPI_SIOO_INST_EVERY_CMD;	// Send a command every time data is transferred
  s_command.AddressMode 			= QSPI_ADDRESS_1_LINE;        // 1-Wire Address Mode
  s_command.DataMode 				= QSPI_DATA_NONE;             // no data
  s_command.DummyCycles 			= 0;                          // Number of empty cycles
  s_command.Address           	= SectorAddress;              // address to erase
  s_command.Instruction	 		= W25Qxx_CMD_BlockErase_64K;  // Block erase command, erase 64K bytes at a time	
  
  // send write enable
  if (QSPI_W25Qxx_WriteEnable() != QSPI_W25Qxx_OK)
  {
    return W25Qxx_ERROR_WriteEnable;	// write enable failed
  }
  // Issue the erase command
  if (HAL_QSPI_Command(&hqspi, &s_command, HAL_QPSI_TIMEOUT_DEFAULT_VALUE) != HAL_OK)
  {
    return W25Qxx_ERROR_Erase;			// Erase failed
  }
  // Use automatic polling flags to wait for the end of the erase
  if (QSPI_W25Qxx_AutoPollingMemReady() != QSPI_W25Qxx_OK)
  {
    return W25Qxx_ERROR_AUTOPOLLING;	// Polling waiting for no response
  }
  return QSPI_W25Qxx_OK;		// Erase successful
}

/**************************************************** ************************************************
*
* Function name: QSPI_W25Qxx_ChipErase
*
* Entry parameters: none
*
* Return value: QSPI_W25Qxx_OK - erase successfully
* W25Qxx_ERROR_Erase - Erase failed
* W25Qxx_ERROR_AUTOPOLLING - polling waiting for no response
*
* Function: perform chip erase operation
*
* Note: 1. According to the erase reference time given in the W25Q64JV data sheet, the typical value is 20s, and the maximum value is 100s
* 2. The actual erasing speed may be greater than 20s or less than 20s
* 3. The longer the flash is used, the longer it takes to erase
*
*************************************************************************************************/

int8_t QSPI_W25Qxx_ChipErase (void)	
{
  QSPI_CommandTypeDef s_command;		// QSPI transfer configuration
  QSPI_AutoPollingTypeDef s_config;	// poll wait configuration parameter
  
  s_command.InstructionMode   	= QSPI_INSTRUCTION_1_LINE;    // 1-Wire Command Mode
  s_command.AddressSize       	= QSPI_ADDRESS_24_BITS;       // 24-bit address mode
  s_command.AlternateByteMode 	= QSPI_ALTERNATE_BYTES_NONE;  //	no alternate bytes 
  s_command.DdrMode           	= QSPI_DDR_MODE_DISABLE;      // Disable DDR mode
  s_command.DdrHoldHalfCycle  	= QSPI_DDR_HHC_ANALOG_DELAY;  // Data delay in DDR mode, not used here
  s_command.SIOOMode          	= QSPI_SIOO_INST_EVERY_CMD;	// Send a command every time data is transferred
  s_command.AddressMode 			= QSPI_ADDRESS_NONE;       	// no address
  s_command.DataMode 				= QSPI_DATA_NONE;             // no data
  s_command.DummyCycles 			= 0;                          // Number of empty cycles
  s_command.Instruction	 		= W25Qxx_CMD_ChipErase;       // Erase command, perform chip erase
  
  // send write enable	
  if (QSPI_W25Qxx_WriteEnable() != QSPI_W25Qxx_OK)
  {
    return W25Qxx_ERROR_WriteEnable;	// write enable failed
  }
  // Issue the erase command
  if (HAL_QSPI_Command(&hqspi, &s_command, HAL_QPSI_TIMEOUT_DEFAULT_VALUE) != HAL_OK)
  {
    return W25Qxx_ERROR_Erase;		 // Erase failed
  }
  
  // Keep querying the W25Qxx_CMD_ReadStatus_REG1 register, and keep comparing the W25Qxx_Status_REG1_BUSY in the read status byte with 0
  // Read bit 0 of status register 1 (read-only), the Busy flag bit, will be set to 1 when erasing/writing data/writing commands, and 0 when idle or communication ends
  
  s_config.Match           = 0;   									//	match value
  s_config.MatchMode       = QSPI_MATCH_MODE_AND;	      	//	AND operation
  s_config.Interval        = 0x10;	                     	//	polling interval
  s_config.AutomaticStop   = QSPI_AUTOMATIC_STOP_ENABLE;	// Auto stop mode
  s_config.StatusBytesSize = 1;	                        	//	Status bytes
  s_config.Mask            = W25Qxx_Status_REG1_BUSY;	   // Masks the status byte received in polling mode and compares only the bits that need to be used
  
  s_command.Instruction    = W25Qxx_CMD_ReadStatus_REG1;	// Read Status Information Register
  s_command.DataMode       = QSPI_DATA_1_LINE;					// 1-Wire Data Mode
  s_command.NbData         = 1;										// Data length
  
  // The typical reference time of W25Q64 chip erase is 20s, the maximum time is 100s, and the timeout waiting value here W25Qxx_ChipErase_TIMEOUT_MAX is 100S	if (HAL_QSPI_AutoPolling(&hqspi, &s_command, &s_config, W25Qxx_ChipErase_TIMEOUT_MAX) != HAL_OK)
  {
    return W25Qxx_ERROR_AUTOPOLLING;	 // Polling waiting for no response
  }
  return QSPI_W25Qxx_OK;
}

/**************************************************** **************************************************** ******
*
* Function name: QSPI_W25Qxx_WritePage
*
* Entry parameters: pBuffer - the data to be written
* WriteAddr - address to write to W25Qxx
* NumByteToWrite - data length, the maximum can only be 256 bytes
*
* Return value: QSPI_W25Qxx_OK - write data successfully
* W25Qxx_ERROR_WriteEnable - write enable failed
* W25Qxx_ERROR_TRANSMIT - transfer failed
* W25Qxx_ERROR_AUTOPOLLING - polling waiting for no response
*
* Function: Write by page, the maximum can only be 256 bytes, please be sure to complete the erase operation before writing data
*
* Note: 1. The writing time of Flash is the same as the erasing time, which is limited. It does not mean that the QSPI drive clock 133M can write at this speed.
* 2. According to the W25Q64JV data sheet page (256 bytes) write reference time, the typical value is 0.4ms, the maximum value is 3ms
* 3. The actual writing speed may be greater than 0.4ms or less than 0.4ms
* 4. The longer the Flash is used, the longer the writing time will be
* 5. Before writing data, be sure to complete the erase operation
*
*************************************************************************************************************/

int8_t QSPI_W25Qxx_WritePage(uint8_t* pBuffer, uint32_t WriteAddr, uint16_t NumByteToWrite)
{
  QSPI_CommandTypeDef s_command;	// QSPI transfer configuration	
  
  s_command.InstructionMode   = QSPI_INSTRUCTION_1_LINE;    		// 1-Wire Command Mode
  s_command.AddressSize       = QSPI_ADDRESS_24_BITS;            // 24-bit address
  s_command.AlternateByteMode = QSPI_ALTERNATE_BYTES_NONE;  		// no alternate bytes 
  s_command.DdrMode           = QSPI_DDR_MODE_DISABLE;     		// Disable DDR mode
  s_command.DdrHoldHalfCycle  = QSPI_DDR_HHC_ANALOG_DELAY; 		// DData delay in DR mode, not used here
  s_command.SIOOMode          = QSPI_SIOO_INST_EVERY_CMD;			// Send a command every time data is transferred	
  s_command.AddressMode 		 = QSPI_ADDRESS_1_LINE; 				// 1-Wire Address Mode
  s_command.DataMode    		 = QSPI_DATA_4_LINES;    				// 4-wire data mode
  s_command.DummyCycles 		 = 0;                    				// Number of empty cycles
  s_command.NbData      		 = NumByteToWrite;      			   // Data length, the maximum can only be 256 bytes
  s_command.Address     		 = WriteAddr;         					// Address to write to W25Qxx
  s_command.Instruction 		 = W25Qxx_CMD_QuadInputPageProgram; // In 1-1-4 mode (1-line command, 1-line address, 4-line data), page programming command
  // write enable
  if (QSPI_W25Qxx_WriteEnable() != QSPI_W25Qxx_OK)
  {
    return W25Qxx_ERROR_WriteEnable;	// write enable failed
  }
  // write command
  if (HAL_QSPI_Command(&hqspi, &s_command, HAL_QPSI_TIMEOUT_DEFAULT_VALUE) != HAL_OK)
  {
    return W25Qxx_ERROR_TRANSMIT;		// Transmission data error
  }
  // start transferring data
  if (HAL_QSPI_Transmit(&hqspi, pBuffer, HAL_QPSI_TIMEOUT_DEFAULT_VALUE) != HAL_OK)
  {
    return W25Qxx_ERROR_TRANSMIT;		// Transmission data error
  }
  // Use automatic polling flags to wait for the end of the write
  if (QSPI_W25Qxx_AutoPollingMemReady() != QSPI_W25Qxx_OK)
  {
    return W25Qxx_ERROR_AUTOPOLLING; // Polling waiting for no response
  }
  return QSPI_W25Qxx_OK;	// write data successfully
}
/**************************************************** **************************************************** ******
*
* Function name: QSPI_W25Qxx_WriteBuffer
*
* Entry parameters: pBuffer - the data to be written
* WriteAddr - address to write to W25Qxx
* NumByteToWrite - data length, the maximum cannot exceed the size of the flash chip
*
* Return value: QSPI_W25Qxx_OK - write data successfully
* W25Qxx_ERROR_WriteEnable - write enable failed
* W25Qxx_ERROR_TRANSMIT - transfer failed
* W25Qxx_ERROR_AUTOPOLLING - polling waiting for no response
*
* Function: write data, the maximum can not exceed the size of the flash chip, please be sure to complete the erase operation
*
* Note: 1. The writing time of Flash is the same as the erasing time, which is limited. It does not mean that the QSPI drive clock 133M can write at this speed.
* 2. According to the page write reference time given in the W25Q64JV data sheet, the typical value is 0.4ms, the maximum value is 3ms
* 3. The actual writing speed may be greater than 0.4ms or less than 0.4ms
* 4. The longer the Flash is used, the longer the writing time will be
* 5. Before writing data, be sure to complete the erase operation
* 6. This function is ported to stm32h743i_eval_qspi.c
*
************************************************************************************************************/

int8_t QSPI_W25Qxx_WriteBuffer(uint8_t* pBuffer, uint32_t WriteAddr, uint32_t Size)
{	
  uint32_t end_addr, current_size, current_addr;
  uint8_t *write_data;  // data to write
  
  current_size = W25Qxx_PageSize - (WriteAddr % W25Qxx_PageSize); // Calculate the space left on the current page
  
  if (current_size > Size)	//Determine whether the remaining space of the current page is enough to write all the data
  {
    current_size = Size;		// If it is enough, get the current length directly
  }
  
  current_addr = WriteAddr;		// Get the address to write to
  end_addr = WriteAddr + Size;	// Calculate end address
  write_data = pBuffer;			// Get data to write
  
  do
  {
    // Write data by page
    if(QSPI_W25Qxx_WritePage(write_data, current_addr, current_size) != QSPI_W25Qxx_OK)
    {
      return W25Qxx_ERROR_TRANSMIT;
    }
    
    else //Write data by page successfully, prepare for the next data write
    {
      current_addr += current_size;	// Calculate the address to be written next
      write_data += current_size;	// Get the address of the data memory area to be written next
      // Calculate the length of the next write data
      current_size = ((current_addr + W25Qxx_PageSize) > end_addr) ? (end_addr - current_addr) : W25Qxx_PageSize;
    }
  }
  while (current_addr < end_addr) ; // Determine whether all data has been written
  
  return QSPI_W25Qxx_OK;	// Write data successfully
  
}

/**************************************************** **************************************************** ********************************
*
* Function name: QSPI_W25Qxx_ReadBuffer
*
* Entry parameters: pBuffer - the data to read
* ReadAddr - address to read W25Qxx
* NumByteToRead - data length, the maximum cannot exceed the size of the flash chip
*
* Return value: QSPI_W25Qxx_OK - read data successfully
* W25Qxx_ERROR_TRANSMIT - transfer failed
* W25Qxx_ERROR_AUTOPOLLING - polling waiting for no response
*
* Function: read data, the maximum cannot exceed the size of the flash chip
*
* Note: 1. The reading speed of Flash depends on the communication clock of QSPI, and the maximum cannot exceed 133M
* 2. The 1-4-4 mode is used here (1-line command 4-line address 4-line data), fast read command Fast Read Quad I/O
* 3. There is a free cycle when using the fast read command. For details, please refer to the Fast Read Quad I/O (0xEB) command in the W25Q64JV manual.
* 4. In actual use, whether DMA is used, the optimization level of the compiler and the location of the data storage area (internal TCM SRAM or AXI SRAM) will affect the reading speed
* 5. In this routine, library functions are used for direct reading and writing, keil version 5.30, compiler AC6.14, compilation level Oz image size, read speed is 7M bytes/S,
* Data is placed in TCM SRAM or AXI SRAM is similar result
* 6. Because the efficiency of CPU directly accessing peripheral registers is very low, if you directly use the HAL library to read and write, the speed is very slow. Using MDMA to read and write can reach 58M bytes/S
* 7. The maximum driving frequency allowed by W25Q64JV is 133MHz, and the maximum driving frequency of QSPI of 750 is also 133MHz, but for direct reading of HAL library functions,
* If the drive clock exceeds 15M, the performance will not be improved. For occasions with high speed requirements, MDMA can be used.
*
****************************************************************************************************************FANKE************/

int8_t QSPI_W25Qxx_ReadBuffer(uint8_t* pBuffer, uint32_t ReadAddr, uint32_t NumByteToRead)
{
  QSPI_CommandTypeDef s_command;	// QSPI transfer configuration
  
  s_command.InstructionMode   = QSPI_INSTRUCTION_1_LINE;    		// 1-Wire Command Mode
  s_command.AddressSize       = QSPI_ADDRESS_24_BITS;            // 24-bit address
  s_command.AlternateByteMode = QSPI_ALTERNATE_BYTES_NONE;  		// no alternate bytes 
  s_command.DdrMode           = QSPI_DDR_MODE_DISABLE;     		// Disable DDR mode
  s_command.DdrHoldHalfCycle  = QSPI_DDR_HHC_ANALOG_DELAY; 		// Data delay in DDR mode, not used here
  s_command.SIOOMode          = QSPI_SIOO_INST_EVERY_CMD;			// Send a command every time data is transferred	
  s_command.AddressMode 		 = QSPI_ADDRESS_4_LINES; 				// 4-Wire Address Mode
  s_command.DataMode    		 = QSPI_DATA_4_LINES;    				// 4-wire data mode
  s_command.DummyCycles 		 = 6;                    				// Number of empty cycles
  s_command.NbData      		 = NumByteToRead;      			   	// Data length, the maximum cannot exceed the size of the flash chip
  s_command.Address     		 = ReadAddr;         					//Address to read W25Qxx
  s_command.Instruction 		 = W25Qxx_CMD_FastReadQuad_IO; 		//In 1-4-4 mode (1-line command, 4-line address, 4-line data), fast read command
  
  // send read command
  if (HAL_QSPI_Command(&hqspi, &s_command, HAL_QPSI_TIMEOUT_DEFAULT_VALUE) != HAL_OK)
  {
    return W25Qxx_ERROR_TRANSMIT;		// Transmission data error
  }
  
  //	Receive data
  
  if (HAL_QSPI_Receive(&hqspi, pBuffer, HAL_QPSI_TIMEOUT_DEFAULT_VALUE) != HAL_OK)
  {
    return W25Qxx_ERROR_TRANSMIT;		// Transmission data error
  }
  // Use the auto polling flag and wait for the end of the receive
  if (QSPI_W25Qxx_AutoPollingMemReady() != QSPI_W25Qxx_OK)
  {
    return W25Qxx_ERROR_AUTOPOLLING; // Polling waiting for no response
  }
  return QSPI_W25Qxx_OK;	// read data successfully
}


// Experimental platform: Anti-ke STM32H750VBT6 core board
/********************************************************************************************************************************************************************************************************FANKE**********/

